use cphf::{OrderedMap, phf_ordered_map};

use crate::{
    lexer::token::{Ident, Keyword, Literal, Op, Punct, Token},
    parser::{
        action::Action,
        non_terminal::NonTerminal::{
            self, AfterStatement, Args, ArgsNext, ArgsTail, Atom, AtomTail, Block, CalledArgs, CalledArgsTail,
            CalledNext, ConstDecl, ConstDeclBody, Decls, E1, E1Tail, E2, E2Tail, E3, E3Tail, E4, E4Tail, E5, E5Tail,
            E6, E6Tail, Expr, ExprStatementTail, FnDecl, ForDir, ForStatement, IfStatement, IfTail, ProcDecl,
            Statement, Statements, Type, VarDecl, VarDeclBody, VarDecls, VarNames, VarNamesTail, WhileStatement,
        },
        stack_symbol::StackSymbol,
    },
};

type A = Action;
type I = Ident;
type K = Keyword;
type L = Literal;
type O = Op;
type P = Punct;
type S = StackSymbol;
type T = Token;

pub static RULES: OrderedMap<usize, &'static [StackSymbol]> = phf_ordered_map! {usize, &'static [S];
    1 => &[S::Terminal(T::Keyword(K::Program)), S::Terminal(T::Ident(I::empty())), S::Terminal(T::Punct(P::Semicolon)), S::NonTerminal(Decls), S::NonTerminal(Block), S::Terminal(T::Punct(P::Dot)), S::Action(A::Program)],
    2 => &[S::NonTerminal(ConstDecl), S::NonTerminal(Decls), S::Action(A::JoinDecls)],
    3 => &[S::NonTerminal(VarDecl), S::NonTerminal(Decls), S::Action(A::JoinDecls)],
    4 => &[S::NonTerminal(ProcDecl), S::NonTerminal(Decls), S::Action(A::InsertDecl)],
    5 => &[S::NonTerminal(FnDecl), S::NonTerminal(Decls), S::Action(A::InsertDecl)],
    6 => &[S::Action(A::EmptyDecls)],
    7 => &[S::Terminal(T::Keyword(K::Const)), S::NonTerminal(ConstDeclBody)],
    8 => &[S::NonTerminal(VarNames), S::Terminal(T::Op(O::Eq)), S::Terminal(T::Literal(L::empty())), S::Terminal(T::Punct(P::Semicolon)), S::NonTerminal(ConstDeclBody), S::Action(A::InsertConstDecl)],
    10 => &[S::Terminal(T::Keyword(K::Var)), S::NonTerminal(VarDeclBody)],
    11 => &[S::NonTerminal(VarNames), S::Terminal(T::Punct(P::Colon)), S::NonTerminal(Type), S::Terminal(T::Punct(P::Semicolon)), S::NonTerminal(VarDeclBody), S::Action(A::InsertVarDecl)],
    13 => &[S::Terminal(T::Keyword(K::Proc)), S::Terminal(T::Ident(I::empty())), S::Terminal(T::Punct(P::LBracket)), S::NonTerminal(Args), S::Terminal(T::Punct(P::RBracket)), S::Terminal(T::Punct(P::Semicolon)), S::NonTerminal(VarDecls), S::NonTerminal(Block), S::Terminal(T::Punct(P::Semicolon)), S::Action(A::ProcDecl)],
    14 => &[S::Terminal(T::Keyword(K::Fn)), S::Terminal(T::Ident(I::empty())), S::Terminal(T::Punct(P::LBracket)), S::NonTerminal(Args), S::Terminal(T::Punct(P::RBracket)), S::Terminal(T::Punct(P::Colon)), S::NonTerminal(Type), S::Terminal(T::Punct(P::Semicolon)), S::NonTerminal(VarDecls), S::NonTerminal(Block), S::Terminal(T::Punct(P::Semicolon)), S::Action(A::FnDecl)],
    15 => &[S::NonTerminal(VarDecl), S::NonTerminal(VarDecls), S::Action(A::JoinDecls)],
    17 => &[S::Terminal(T::Keyword(K::Int)), S::Action(A::TypeInt)],
    18 => &[S::Terminal(T::Keyword(K::Real)), S::Action(A::TypeReal)],
    19 => &[S::Terminal(T::Keyword(K::Bool)), S::Action(A::TypeBool)],
    20 => &[S::Terminal(T::Keyword(K::Array)), S::Terminal(T::Punct(P::LSquareBracket)), S::Terminal(T::Literal(L::empty())), S::Terminal(T::Punct(P::DotDot)), S::Terminal(T::Literal(L::empty())), S::Terminal(T::Punct(P::RSquareBracket)), S::Terminal(T::Keyword(K::Of)), S::NonTerminal(Type), S::Action(A::TypeArray)],
    21 => &[S::Terminal(T::Ident(I::empty())), S::Terminal(T::Punct(P::Colon)), S::NonTerminal(Type), S::NonTerminal(ArgsTail), S::Action(A::InsertArg)],
    22 => &[S::Action(A::EmptyParams)],
    23 => &[S::Terminal(T::Punct(P::Comma)), S::NonTerminal(ArgsNext)],
    25 => &[S::Terminal(T::Ident(I::empty())), S::Terminal(T::Punct(P::Colon)), S::NonTerminal(Type), S::NonTerminal(ArgsTail), S::Action(A::InsertArg)],
    27 => &[S::Terminal(T::Ident(I::empty())), S::NonTerminal(VarNamesTail), S::Action(A::InsertIdent)],
    28 => &[S::Terminal(T::Punct(P::Comma)), S::Terminal(T::Ident(I::empty())), S::NonTerminal(VarNamesTail), S::Action(A::InsertIdent)],
    29 => &[S::Action(A::EmptyVarNames)],
    30 => &[S::Terminal(T::Punct(P::LCurlyBracket)), S::NonTerminal(Statements), S::Terminal(T::Punct(P::RCurlyBracket)), S::Action(A::Block)],
    31 => &[S::NonTerminal(Statement), S::NonTerminal(AfterStatement), S::Action(A::InsertStatement)],
    32 => &[S::Action(A::EmptyStatements)],
    33 => &[S::Terminal(T::Punct(P::Semicolon)), S::NonTerminal(Statements)],
    35 => &[S::NonTerminal(Block), S::Action(A::StatementBlock)],
    36 => &[S::NonTerminal(IfStatement)],
    37 => &[S::NonTerminal(WhileStatement)],
    38 => &[S::NonTerminal(ForStatement)],
    39 => &[S::NonTerminal(Expr), S::NonTerminal(ExprStatementTail), S::Action(A::StatementExpr)],
    40 => &[S::Terminal(T::Keyword(K::Break)), S::Action(A::StatementBreak)],
    41 => &[S::Terminal(T::Keyword(K::Continue)), S::Action(A::StatementContinue)],
    42 => &[S::Terminal(T::Keyword(K::Exit)), S::Action(A::StatementExit)],
    43 => &[S::Terminal(T::Keyword(K::If)), S::NonTerminal(Expr), S::Terminal(T::Keyword(K::Then)), S::NonTerminal(Statement), S::NonTerminal(IfTail), S::Action(A::StatementIf)],
    44 => &[S::Terminal(T::Keyword(K::Else)), S::NonTerminal(Statement), S::Action(A::IfTail)],
    45 => &[S::Action(A::EmptyIfTail)],
    46 => &[S::Terminal(T::Keyword(K::While)), S::NonTerminal(Expr), S::Terminal(T::Keyword(K::Do)), S::NonTerminal(Statement), S::Action(A::StatementWhile)],
    47 => &[S::Terminal(T::Keyword(K::For)), S::Terminal(T::Ident(I::empty())), S::Terminal(T::Op(O::Assign)), S::NonTerminal(Expr), S::NonTerminal(ForDir), S::NonTerminal(Expr), S::Terminal(T::Keyword(K::Do)), S::NonTerminal(Statement), S::Action(A::StatementFor)],
    48 => &[S::Terminal(T::Keyword(K::To)), S::Action(A::ForDirTo)],
    49 => &[S::Terminal(T::Keyword(K::Downto)), S::Action(A::ForDirDownto)],
    50 => &[S::Terminal(T::Op(O::Assign)), S::NonTerminal(Expr), S::Action(A::ExprTail)],
    51 => &[S::Action(A::ExprTailEmpty)],
    54 => &[S::NonTerminal(Expr), S::NonTerminal(CalledArgsTail), S::Action(A::InsertCalledArgs)],
    55 => &[S::Action(A::EmptyCalledArgs)],
    56 => &[S::Terminal(T::Punct(P::Comma)), S::NonTerminal(CalledNext)],
    58 => &[S::NonTerminal(Expr), S::NonTerminal(CalledArgsTail), S::Action(A::InsertCalledArgs)],
    60 => &[S::NonTerminal(E1), S::NonTerminal(E1Tail), S::Action(A::Expr)],
    61 => &[S::NonTerminal(E2), S::NonTerminal(E2Tail), S::Action(A::Expr)],
    62 => &[S::NonTerminal(E3), S::NonTerminal(E3Tail), S::Action(A::Expr)],
    63 => &[S::NonTerminal(E4), S::NonTerminal(E4Tail), S::Action(A::Expr)],
    64 => &[S::NonTerminal(E5), S::NonTerminal(E5Tail), S::Action(A::Expr)],
    65 => &[S::NonTerminal(E6), S::NonTerminal(E6Tail), S::Action(A::Expr)],
    66 => &[S::Terminal(T::Op(O::Not)), S::NonTerminal(E6), S::Action(A::UnaryNot)],
    67 => &[S::Terminal(T::Op(O::Minus)), S::NonTerminal(E6), S::Action(A::UnaryMinus)],
    68 => &[S::Terminal(T::Op(O::Plus)), S::NonTerminal(E6), S::Action(A::UnaryPlus)],
    69 => &[S::NonTerminal(Atom)],
    70 => &[S::Terminal(T::Op(O::Equiv)), S::NonTerminal(E2), S::NonTerminal(E1Tail), S::Action(A::TailEquiv)],
    71 => &[S::Terminal(T::Op(O::Imply)), S::NonTerminal(E2), S::NonTerminal(E1Tail), S::Action(A::TailImply)],
    72 => &[S::Action(A::TailEmpty)],
    73 => &[S::Terminal(T::Op(O::Or)), S::NonTerminal(E3), S::NonTerminal(E2Tail), S::Action(A::TailOr)],
    74 => &[S::Terminal(T::Op(O::Xor)), S::NonTerminal(E3), S::NonTerminal(E2Tail), S::Action(A::TailXor)],
    76 => &[S::Terminal(T::Op(O::And)), S::NonTerminal(E4), S::NonTerminal(E3Tail), S::Action(A::TailAnd)],
    78 => &[S::Terminal(T::Op(O::Eq)), S::NonTerminal(E5), S::Action(A::TailEq)],
    79 => &[S::Terminal(T::Op(O::Neq)), S::NonTerminal(E5), S::Action(A::TailNeq)],
    80 => &[S::Terminal(T::Op(O::Lt)), S::NonTerminal(E5), S::Action(A::TailLt)],
    81 => &[S::Terminal(T::Op(O::Gt)), S::NonTerminal(E5), S::Action(A::TailGt)],
    82 => &[S::Terminal(T::Op(O::Leq)), S::NonTerminal(E5), S::Action(A::TailLeq)],
    83 => &[S::Terminal(T::Op(O::Geq)), S::NonTerminal(E5), S::Action(A::TailGeq)],
    85 => &[S::Terminal(T::Op(O::Plus)), S::NonTerminal(E5), S::NonTerminal(E5Tail), S::Action(A::TailPlus)],
    86 => &[S::Terminal(T::Op(O::Minus)), S::NonTerminal(E5), S::NonTerminal(E5Tail), S::Action(A::TailMinus)],
    88 => &[S::Terminal(T::Op(O::Times)), S::NonTerminal(E6), S::NonTerminal(E6Tail), S::Action(A::TailTimes)],
    89 => &[S::Terminal(T::Op(O::Div)), S::NonTerminal(E6), S::NonTerminal(E6Tail), S::Action(A::TailDiv)],
    90 => &[S::Terminal(T::Op(O::Mod)), S::NonTerminal(E6), S::NonTerminal(E6Tail), S::Action(A::TailMod)],
    92 => &[S::Terminal(T::Ident(I::empty())), S::NonTerminal(AtomTail), S::Action(A::AtomIdent)],
    93 => &[S::Terminal(T::Literal(L::empty())), S::NonTerminal(AtomTail), S::Action(A::AtomLiteral)],
    94 => &[S::Terminal(T::Punct(P::LBracket)), S::NonTerminal(Expr), S::Terminal(T::Punct(P::RBracket)), S::NonTerminal(AtomTail), S::Action(A::AtomGroup)],
    95 => &[S::Terminal(T::Punct(P::LSquareBracket)), S::NonTerminal(Expr), S::Terminal(T::Punct(P::RSquareBracket)), S::NonTerminal(AtomTail), S::Action(A::InsertIndex)],
    96 => &[S::Terminal(T::Punct(P::LBracket)), S::NonTerminal(CalledArgs), S::Terminal(T::Punct(P::RBracket)), S::NonTerminal(AtomTail), S::Action(A::InsertCall)],
    97 => &[S::Action(A::EmptyPostfixTail)],
};

pub static PARSING_TABLE: OrderedMap<NonTerminal, OrderedMap<Token, usize>> = phf_ordered_map! {NonTerminal, OrderedMap<Token, usize>;
    NonTerminal::S => phf_ordered_map! {Token, usize;
        T::Keyword(K::Program) => 1,
    },
    Decls => phf_ordered_map! {Token, usize;
        T::Keyword(K::Const) => 2,
        T::Keyword(K::Var) => 3,
        T::Keyword(K::Proc) => 4,
        T::Keyword(K::Fn) => 5,
        T::Punct(P::LCurlyBracket) => 6,
    },
    ConstDecl => phf_ordered_map! {Token, usize;
        T::Keyword(K::Const) => 7,
    },
    ConstDeclBody => phf_ordered_map! {Token, usize;
        T::Ident(I::empty()) => 8,
        T::Keyword(K::Const) => 6,
        T::Keyword(K::Var) => 6,
        T::Keyword(K::Proc) => 6,
        T::Keyword(K::Fn) => 6,
        T::Punct(P::LCurlyBracket) => 6,
    },
    VarDecl => phf_ordered_map! {Token, usize;
        T::Keyword(K::Var) => 10,
    },
    VarDeclBody => phf_ordered_map! {Token, usize;
        T::Ident(I::empty()) => 11,
        T::Keyword(K::Const) => 6,
        T::Keyword(K::Var) => 6,
        T::Keyword(K::Proc) => 6,
        T::Keyword(K::Fn) => 6,
        T::Punct(P::LCurlyBracket) => 6,
    },
    ProcDecl => phf_ordered_map! {Token, usize;
        T::Keyword(K::Proc) => 13,
    },
    FnDecl => phf_ordered_map! {Token, usize;
        T::Keyword(K::Fn) => 14,
    },
    VarDecls => phf_ordered_map! {Token, usize;
        T::Keyword(K::Var) => 15,
        T::Punct(P::LCurlyBracket) => 6,
    },
    Type => phf_ordered_map! {Token, usize;
        T::Keyword(K::Int) => 17,
        T::Keyword(K::Real) => 18,
        T::Keyword(K::Bool) => 19,
        T::Keyword(K::Array) => 20,
    },
    Args => phf_ordered_map! {Token, usize;
        T::Ident(I::empty()) => 21,
        T::Punct(P::RBracket) => 22,
    },
    ArgsTail => phf_ordered_map! {Token, usize;
        T::Punct(P::Comma) => 23,
        T::Punct(P::RBracket) => 22,
    },
    ArgsNext => phf_ordered_map! {Token, usize;
        T::Ident(I::empty()) => 25,
        T::Punct(P::RBracket) => 22,
    },
    VarNames => phf_ordered_map! {Token, usize;
        T::Ident(I::empty()) => 27,
    },
    VarNamesTail => phf_ordered_map! {Token, usize;
        T::Punct(P::Comma) => 28,
        T::Op(O::Eq) => 29,
        T::Punct(P::Colon) => 29,
    },
    Block => phf_ordered_map! {Token, usize;
        T::Punct(P::LCurlyBracket) => 30,
    },
    Statements => phf_ordered_map! {Token, usize;
        T::Keyword(K::Break) => 31,
        T::Keyword(K::Continue) => 31,
        T::Keyword(K::Exit) => 31,
        T::Keyword(K::If) => 31,
        T::Keyword(K::While) => 31,
        T::Keyword(K::For) => 31,
        T::Punct(P::LCurlyBracket) => 31,
        T::Ident(I::empty()) => 31,
        T::Punct(P::RCurlyBracket) => 32,
    },
    AfterStatement => phf_ordered_map! {Token, usize;
        T::Punct(P::Semicolon) => 33,
        T::Punct(P::RCurlyBracket) => 32,
    },
    Statement => phf_ordered_map! {Token, usize;
        T::Punct(P::LCurlyBracket) => 35,
        T::Keyword(K::If) => 36,
        T::Keyword(K::While) => 37,
        T::Keyword(K::For) => 38,
        T::Ident(I::empty()) => 39,
        T::Literal(L::empty()) => 39,
        T::Punct(P::LBracket) => 39,
        T::Op(O::Plus) => 39,
        T::Op(O::Minus) => 39,
        T::Op(O::Not) => 39,
        T::Keyword(K::Break) => 40,
        T::Keyword(K::Continue) => 41,
        T::Keyword(K::Exit) => 42,
    },
    IfStatement => phf_ordered_map! {Token, usize;
        T::Keyword(K::If) => 43,
    },
    IfTail => phf_ordered_map! {Token, usize;
        T::Keyword(K::Else) => 44,
        T::Punct(P::Semicolon) => 45,
        T::Punct(P::RCurlyBracket) => 45,
    },
    WhileStatement => phf_ordered_map! {Token, usize;
        T::Keyword(K::While) => 46,
    },
    ForStatement => phf_ordered_map! {Token, usize;
        T::Keyword(K::For) => 47,
    },
    ForDir => phf_ordered_map! {Token, usize;
        T::Keyword(K::To) => 48,
        T::Keyword(K::Downto) => 49,
    },
    ExprStatementTail => phf_ordered_map! {Token, usize;
        T::Op(O::Assign) => 50,
        T::Punct(P::Semicolon) => 51,
        T::Punct(P::RCurlyBracket) => 51,
        T::Keyword(K::Else) => 51,
    },
    CalledArgs => phf_ordered_map! {Token, usize;
        T::Punct(P::LBracket) => 54,
        T::Op(O::Plus) => 54,
        T::Op(O::Minus) => 54,
        T::Op(O::Not) => 54,
        T::Ident(I::empty()) => 54,
        T::Literal(L::empty()) => 54,
        T::Punct(P::RBracket) => 55,
    },
    CalledArgsTail => phf_ordered_map! {Token, usize;
        T::Punct(P::Comma) => 56,
        T::Punct(P::RBracket) => 55,
    },
    CalledNext => phf_ordered_map! {Token, usize;
        T::Punct(P::LBracket) => 58,
        T::Op(O::Plus) => 58,
        T::Op(O::Minus) => 58,
        T::Op(O::Not) => 58,
        T::Ident(I::empty()) => 58,
        T::Literal(L::empty()) => 58,
        T::Punct(P::RBracket) => 55,
    },
    Expr => phf_ordered_map! {Token, usize;
        T::Punct(P::LBracket) => 60,
        T::Op(O::Plus) => 60,
        T::Op(O::Minus) => 60,
        T::Op(O::Not) => 60,
        T::Ident(I::empty()) => 60,
        T::Literal(L::empty()) => 60,
    },
    E1 => phf_ordered_map! {Token, usize;
        T::Punct(P::LBracket) => 61,
        T::Op(O::Plus) => 61,
        T::Op(O::Minus) => 61,
        T::Op(O::Not) => 61,
        T::Ident(I::empty()) => 61,
        T::Literal(L::empty()) => 61,
    },
    E2 => phf_ordered_map! {Token, usize;
        T::Punct(P::LBracket) => 62,
        T::Op(O::Plus) => 62,
        T::Op(O::Minus) => 62,
        T::Op(O::Not) => 62,
        T::Ident(I::empty()) => 62,
        T::Literal(L::empty()) => 62,
    },
    E3 => phf_ordered_map! {Token, usize;
        T::Punct(P::LBracket) => 63,
        T::Op(O::Plus) => 63,
        T::Op(O::Minus) => 63,
        T::Op(O::Not) => 63,
        T::Ident(I::empty()) => 63,
        T::Literal(L::empty()) => 63,
    },
    E4 => phf_ordered_map! {Token, usize;
        T::Punct(P::LBracket) => 64,
        T::Op(O::Plus) => 64,
        T::Op(O::Minus) => 64,
        T::Op(O::Not) => 64,
        T::Ident(I::empty()) => 64,
        T::Literal(L::empty()) => 64,
    },
    E5 => phf_ordered_map! {Token, usize;
        T::Punct(P::LBracket) => 65,
        T::Op(O::Plus) => 65,
        T::Op(O::Minus) => 65,
        T::Op(O::Not) => 65,
        T::Ident(I::empty()) => 65,
        T::Literal(L::empty()) => 65,
    },
    E6 => phf_ordered_map! {Token, usize;
        T::Punct(P::LBracket) => 69,
        T::Op(O::Plus) => 68,
        T::Op(O::Minus) => 67,
        T::Op(O::Not) => 66,
        T::Ident(I::empty()) => 69,
        T::Literal(L::empty()) => 69,
    },
    E1Tail => phf_ordered_map! {Token, usize;
        T::Op(O::Equiv) => 70,
        T::Op(O::Imply) => 71,
        T::Keyword(K::Then) => 72,
        T::Keyword(K::Do) => 72,
        T::Keyword(K::To) => 72,
        T::Keyword(K::Downto) => 72,
        T::Punct(P::Semicolon) => 72,
        T::Punct(P::RCurlyBracket) => 72,
        T::Punct(P::RSquareBracket) => 72,
        T::Punct(P::Comma) => 72,
        T::Punct(P::RBracket) => 72,
        T::Keyword(K::Else) => 72,
        T::Op(O::Assign) => 72,
    },
    E2Tail => phf_ordered_map! {Token, usize;
        T::Op(O::Or) => 73,
        T::Op(O::Xor) => 74,
        T::Keyword(K::Then) => 72,
        T::Keyword(K::Do) => 72,
        T::Keyword(K::To) => 72,
        T::Keyword(K::Downto) => 72,
        T::Punct(P::Semicolon) => 72,
        T::Punct(P::RCurlyBracket) => 72,
        T::Punct(P::RSquareBracket) => 72,
        T::Punct(P::Comma) => 72,
        T::Punct(P::RBracket) => 72,
        T::Keyword(K::Else) => 72,
        T::Op(O::Equiv) => 72,
        T::Op(O::Imply) => 72,
        T::Op(O::Assign) => 72,
    },
    E3Tail => phf_ordered_map! {Token, usize;
        T::Op(O::And) => 76,
        T::Keyword(K::Then) => 72,
        T::Keyword(K::Do) => 72,
        T::Keyword(K::To) => 72,
        T::Keyword(K::Downto) => 72,
        T::Punct(P::Semicolon) => 72,
        T::Punct(P::RCurlyBracket) => 72,
        T::Punct(P::RSquareBracket) => 72,
        T::Punct(P::Comma) => 72,
        T::Punct(P::RBracket) => 72,
        T::Keyword(K::Else) => 72,
        T::Op(O::Or) => 72,
        T::Op(O::Xor) => 72,
        T::Op(O::Equiv) => 72,
        T::Op(O::Imply) => 72,
        T::Op(O::Assign) => 72,
    },
    E4Tail => phf_ordered_map! {Token, usize;
        T::Op(O::Eq) => 78,
        T::Op(O::Neq) => 79,
        T::Op(O::Lt) => 80,
        T::Op(O::Gt) => 81,
        T::Op(O::Leq) => 82,
        T::Op(O::Geq) => 83,
        T::Op(O::And) => 72,
        T::Op(O::Or) => 72,
        T::Op(O::Xor) => 72,
        T::Keyword(K::Then) => 72,
        T::Keyword(K::Do) => 72,
        T::Keyword(K::To) => 72,
        T::Keyword(K::Downto) => 72,
        T::Punct(P::Semicolon) => 72,
        T::Punct(P::RCurlyBracket) => 72,
        T::Punct(P::RSquareBracket) => 72,
        T::Punct(P::Comma) => 72,
        T::Punct(P::RBracket) => 72,
        T::Keyword(K::Else) => 72,
        T::Op(O::Equiv) => 72,
        T::Op(O::Imply) => 72,
        T::Op(O::Assign) => 72,
    },
    E5Tail => phf_ordered_map! {Token, usize;
        T::Op(O::Plus) => 85,
        T::Op(O::Minus) => 86,
        T::Op(O::Eq) => 72,
        T::Op(O::Neq) => 72,
        T::Op(O::Lt) => 72,
        T::Op(O::Gt) => 72,
        T::Op(O::Leq) => 72,
        T::Op(O::Geq) => 72,
        T::Op(O::And) => 72,
        T::Op(O::Or) => 72,
        T::Op(O::Xor) => 72,
        T::Keyword(K::Then) => 72,
        T::Keyword(K::Do) => 72,
        T::Keyword(K::To) => 72,
        T::Keyword(K::Downto) => 72,
        T::Punct(P::Semicolon) => 72,
        T::Punct(P::RCurlyBracket) => 72,
        T::Punct(P::RSquareBracket) => 72,
        T::Punct(P::Comma) => 72,
        T::Punct(P::RBracket) => 72,
        T::Keyword(K::Else) => 72,
        T::Op(O::Equiv) => 72,
        T::Op(O::Imply) => 72,
        T::Op(O::Assign) => 72,
    },
    E6Tail => phf_ordered_map! {Token, usize;
        T::Op(O::Times) => 88,
        T::Op(O::Div) => 89,
        T::Op(O::Mod) => 90,
        T::Op(O::Plus) => 72,
        T::Op(O::Minus) => 72,
        T::Op(O::Eq) => 72,
        T::Op(O::Neq) => 72,
        T::Op(O::Lt) => 72,
        T::Op(O::Gt) => 72,
        T::Op(O::Leq) => 72,
        T::Op(O::Geq) => 72,
        T::Op(O::And) => 72,
        T::Op(O::Or) => 72,
        T::Op(O::Xor) => 72,
        T::Keyword(K::Then) => 72,
        T::Keyword(K::Do) => 72,
        T::Keyword(K::To) => 72,
        T::Keyword(K::Downto) => 72,
        T::Punct(P::Semicolon) => 72,
        T::Punct(P::RCurlyBracket) => 72,
        T::Punct(P::RSquareBracket) => 72,
        T::Punct(P::Comma) => 72,
        T::Punct(P::RBracket) => 72,
        T::Keyword(K::Else) => 72,
        T::Op(O::Equiv) => 72,
        T::Op(O::Imply) => 72,
        T::Op(O::Assign) => 72,
    },
    Atom => phf_ordered_map! {Token, usize;
        T::Ident(I::empty()) => 92,
        T::Literal(L::empty()) => 93,
        T::Punct(P::LBracket) => 94,
    },
    AtomTail => phf_ordered_map! {Token, usize;
        T::Punct(P::LSquareBracket) => 95,
        T::Punct(P::LBracket) => 96,
        T::Op(O::Times) => 97,
        T::Op(O::Div) => 97,
        T::Op(O::Mod) => 97,
        T::Op(O::Plus) => 97,
        T::Op(O::Minus) => 97,
        T::Op(O::Eq) => 97,
        T::Op(O::Neq) => 97,
        T::Op(O::Lt) => 97,
        T::Op(O::Gt) => 97,
        T::Op(O::Leq) => 97,
        T::Op(O::Geq) => 97,
        T::Op(O::And) => 97,
        T::Op(O::Or) => 97,
        T::Op(O::Xor) => 97,
        T::Op(O::Equiv) => 97,
        T::Op(O::Imply) => 97,
        T::Keyword(K::Then) => 97,
        T::Keyword(K::Do) => 97,
        T::Keyword(K::To) => 97,
        T::Keyword(K::Downto) => 97,
        T::Punct(P::Semicolon) => 97,
        T::Punct(P::RCurlyBracket) => 97,
        T::Punct(P::RSquareBracket) => 97,
        T::Punct(P::Comma) => 97,
        T::Punct(P::RBracket) => 97,
        T::Keyword(K::Else) => 97,
        T::Op(O::Assign) => 97,
    },
};
